# Generated by Django 3.0.6 on 2020-06-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='information',
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, choices=[('ST', 'Student'), ('PR', 'Programmer'), ('EN', 'Engineer'), ('ML', 'Machine Learning engineer')], max_length=2, null=True),
        ),
    ]
