# Generated by Django 3.0.6 on 2020-06-03 00:39

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200603_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_img.svg', height_field='height_field', null=True, upload_to=profiles.models.upload_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, choices=[('ST', 'Student'), ('PR', 'Programmer'), ('EN', 'Engineer'), ('ML', 'Machine Learning engineer'), ('OR', 'Other')], max_length=2, null=True),
        ),
    ]
