# Generated by Django 3.0.6 on 2020-06-03 02:16

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200603_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_img.png', height_field='height_field', null=True, upload_to=profiles.models.upload_location, width_field='width_field'),
        ),
    ]
