# Generated by Django 2.2 on 2020-06-05 09:08

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200605_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to=profiles.models.upload_avatar),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_location),
        ),
    ]
