# Generated by Django 3.0.7 on 2020-06-09 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
