# Generated by Django 2.2 on 2020-06-05 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_auto_20200605_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
